#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# wrapper to gain elevated privileges

"""
    Copyright (C) 2018  Jean-Christophe Francois

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import sys
import subprocess

command = ['sudo', '/usr/lib/etcetera/parser.py']

for argument in sys.argv[1:]:
    command.append(argument)

print(command)

subprocess.check_call(command)
